server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://topper1:topper@localhost:27017/topper_db?authSource=admin
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5434/squad-db
    username: admin
    password: 123@mudar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

